### ISSUE TITLE
How should carry-over issues be handled?

### ISSUE THREAD

**Issue by FROGbots-4634** [FIRST-Tech-Challenge/SkyStone#1]
Several issues from the old repo, (such as [this](https://github.com/ftctechnh/ftc_app/issues/577)) still apply to v5.x. How should these be handled? Should they be migrated to this repo and closed on the old repo? Or should they remain in-place on the old repo? Or something else?

**Comment by ftctechnh** [comment]
If an issue still persists, I think it would be easier to track if it were migrated to the current season-specific repository's issue tracking DB.

**Comment by FROGbots-4634** [comment]
Should the old issues be closed when migrated?

**Comment by ftctechnh** [comment]
Yes please.

**Comment by ftctechnh** [comment]
just realized that users might not have ability to delete their issues on the old DB (oops!  sorry - forgot about that).  If you transfer an issue from the old to the new, please flag the old one with a post to indicate that it can be closed.

Thanks!

**Comment by AlecHub** [comment]
Perhaps create a repository dedicated to Issues and Engineering Wiki so that these don't need to get migrated every season.  Also, put the .md files of the Wiki under version control so that we can see the history and so that we can get an email notification when new stuff gets added to the Wiki.

**Comment by FROGbots-4634** [comment]
> 
> 
> Perhaps create a repository dedicated to Issues and Engineering Wiki so that these don't need to get migrated every season. Also, put the .md files of the Wiki under version control so that we can see the history and so that we can get an email notification when new stuff gets added to the Wiki.

The engineering Wikis are already under VCS if I'm not mistaken: https://github.com/FIRST-Tech-Challenge/WikiSupport

**Comment by AlecHub** [comment]
>> The engineering Wikis are already under VCS if I'm not mistaken: https://github.com/FIRST-Tech-Challenge/WikiSupport

Looks like that repo is just storing the assets of the wiki (image files and such).  So if you add the .md files of the Wiki to that repo (instead of using the Wiki feature) you get email notifications and history.

**Comment by cmacfarl** [comment]
Migrating every season, is as @AlecHub noted, somewhat non-optimal.   For now if there's something someone really cares about it should likely be migrated.  In the future, however, FIRST does need a better solution.
