### ISSUE TITLE
PIDF

### ISSUE THREAD

**Issue by David10238** [FIRST-Tech-Challenge/SkyStone#13]
I would like to know how the PIDF algorithm works behind the scenes. Documentation I've seen appears to be PID on velocity error + velocityTarget * F. My main question is, does the algorithm have anything for preventing integral windup, or is that just the job of limiting the max speed?

**Comment by FROGbots-4634** [comment]
FYI: https://github.com/ftctechnh/ftc_app/issues/598

**Comment by AustinShalit** [comment]
As @FROGbots-4634 suggested, take a look at the linked issue.  One thing that thread does not answer is "does the algorithm have anything for preventing integral windup"?

The algorithm does have something to prevent integral windup.  Total error is clamped to the `maximum output / ki`.  This means that the integral term cannot request more than 100% output from the motor.

**Comment by FROGbots-4634** [comment]
> 
> 
> As @FROGbots-4634 suggested, take a look at the linked issue. One thing that thread does not answer is "does the algorithm have anything for preventing integral windup"?
> 
> The algorithm does have something to prevent integral windup. Total error is clamped to the `maximum output / ki`. This means that the integral term cannot request more than 100% output from the motor.

Hmmm..... that is very interesting because 11115's coach (who is in contact with REV) told me a few weeks ago that the algorithm does **not** have any anti-windup clamping.

**Comment by robogreg** [comment]
@AustinShalit is correct on this, he would know as he was a contributing developer to the project ;-)
