### ISSUE TITLE
BUG:  Blockly + Safari(?) losing team programs

### ISSUE THREAD

**Issue by penrods** [FIRST-Tech-Challenge/SkyStone#142]
Yesterday at a meet I learned of a serious Blockly bug that is impacting young teams.  Although I haven't experience it myself, the impact of this is serious enough that I think it needs addressed ASAP.

**Apparent Sequence of  Events:**
* Team writes code
* Someone opens up Blockly on a Mac/iOS device, makes a change, saves it
* Code runs fine on the robot
* Coder reopens Blockly.  All programs are gone.

According to a description/workaround on [Reddit](https://www.reddit.com/r/FTC/comments/dx36dk/blocks_in_onbot_block_mode_vanished_managed_to/?utm_medium=android_app&utm_source=share), the issue involves spaces being replaced by "&amp;nbsp;" at some point in that cycle.  I know Safari isn't recommended, but solving this sounds pretty simple and the consequences of doing something that appears to work are severe.  With some effort is is possible to recover the programs, but novice teams are more likely to just start over and/or just get discouraged.

**Comment by cwm9cwm9** [comment]
I am the person who wrote the Reddit post.  The problem occured while saving from an iPad.  I am attaching an example of the corrupt file.

[nbsp contaminated.zip](https://github.com/FIRST-Tech-Challenge/SkyStone/files/3856316/nbsp.contaminated.zip)

**Comment by lizlooney** [comment]
@cwm9cwm9  Your details were really valuable. I've tracked down the cause of the problem. Thank you!
