### ISSUE TITLE
Can't press the Init Button

### ISSUE THREAD

**Issue by serb1231** [FIRST-Tech-Challenge/SkyStone#159]
We have 2 Samsung Galaxy S5 phones(android version 6.1).We have connected the RC to the Robot(witch has 4 motors and 2 servo-motors),it is detecting the components,the phones are connected through wifi direct,but when we try to press the Init Button,we can see the play button for a fraction of a second but then it goes back to the init button.We tried restarting the phones and taking out the battery,but it doesn't work

**Comment by cmacfarl** [comment]
See https://github.com/ftctechnh/ftc_app/issues/747

**Comment by serb1231** [comment]
Thanks
