### ISSUE TITLE
Consider supporting calling custom Java classes from Blocks OpModes

### ISSUE THREAD

**Issue by lizlooney** [FIRST-Tech-Challenge/SkyStone#161]
See this [post](https://ftcforum.firstinspires.org/forum/ftc-technology/blocks-programming/53219-calling-custom-java-classes-from-blocks-opmodes) from the forum.

**Comment by lizlooney** [comment]
This has been fixed in version 5.5. https://github.com/FIRST-Tech-Challenge/SkyStone#version-55-20200824-090813

**Comment by TimVargo** [comment]
Thank you Liz!  I look forward to trying this new feature out.
