### ISSUE TITLE
Telemetry.Item does not respect format argument

### ISSUE THREAD

**Issue by guberti** [FIRST-Tech-Challenge/SkyStone#17]
When a `Telemetry.Item` object is created with `Telemetry.Line.addData("X", "%.1f", -1)`, the format parameter is ignored when `setValue` is later called on the `Item` object.

Code to reproduce: the below code prints the full value of `localizer.x()` to the console, instead of just one decimal place of precision like it should.

```java
Telemetry.Line odometryLine = telemetry.addLine();
Telemetry.Item telXOdometry = odometryLine.addData("X", "%.1f", -1);
telXOdometry.setValue(localizer.x());
telemetry.update();
```

**Comment by FROGbots-4634** [comment]
I think that is the intended behavior. If you want to format it, I think you need to use:

```java
        /**
         * Updates the value of this item to be the result of the indicated string formatting operation.
         * @param format    the format of the data
         * @param args      the arguments associated with the format
         * @return the receiver
         * @see #addData(String, String, Object...)
         */
        Item setValue(String format, Object...args);
```

**Comment by cmacfarl** [comment]
By calling setValue() without the formatting args you are effectively throwing away the formatting you specified in addData().   Use the methog @FROGbots-4634 mentions and you should get the results you want.  

Also, please make sure to take a close look at the ConceptTelemetry example OpMode.
