### ISSUE TITLE
initialization is slow when there is a "problem with imu"

### ISSUE THREAD

**Issue by LetianLi** [FIRST-Tech-Challenge/SkyStone#209]
On some occasions, we would get the problem with imu issue popping up. If this happens when initializing, it seems to take at least 2 seconds longer than normal to initialize the program. The problem with this is that we can't safely stop the program when it is trying to initialize the imu without it going to "stuck in stop()"

**Comment by FROGbots-4634** [comment]
SDK v5.4 fixes the stuck in stop error when initializing the IMU.
