### ISSUE TITLE
Same issue after complete reinstall of Android Studio and Ftc/Skystone. 

### ISSUE THREAD

**Issue by devinhunsberger** [FIRST-Tech-Challenge/SkyStone#215]
I had an issue open before then closed it thinking I had fixed my problem but I ended up making it much worse. When I install all the files (following all steps given to install) I get an error that the script release-aar.gradle cannot be read, I checked my files and the file doesn't even exist. Not sure if It's a problem on FTC's end or OpenCV but the error is located in the FTC Skystone build.gradle for Teamcode. Any help on this issue would be greatly appreciated. It always seems to happen when I install EasyOpenCV (I'm on a Mac).

**Comment by devinhunsberger** [comment]
Okay so I did some researching, so I noticed you never directly stated that someone had to import the module, and dig some digging finding a team that had the same error (release-aar.gradle) and were told to not import the module. I'll test tomorrow but am I correct that you should not import the module as how you would normally do it?

**Comment by FROGbots-4634** [comment]
Did you mean to open this on the EasyOpenCV issue tracker? In any case, that's correct, do NOT import the module. Follow the instructions verbatim.

**Comment by cmacfarl** [comment]
Please move this issue to the EasyOpenCV repo.
