### ISSUE TITLE
Error getting REV Color/Distance Sensor V3 Working

### ISSUE THREAD

**Issue by Aidan9381** [FIRST-Tech-Challenge/SkyStone#216]
When I tried to add a color sensor, I constantly have a warning saying problem with colSens. I'm pretty sure the issue is that I need to select the REV Color/Distance Sensor V3, but I dont have that as an option in my config, only the REV Color/Range Sensor. How do I get the V3 Sensor to appear in my configuration sections, or is it a problem with a color sensor in general that I'm not aware of?

**Comment by FROGbots-4634** [comment]
Are you using SDK v5.1 or newer? Also, are you on a Control Hub, or a phone for the RC? Finally, dumb question, but did you try to scroll down on the drop down of I2C devices?

**Comment by AlecHub** [comment]
>  … I'm pretty sure the issue is that I need to select the REV Color/Distance Sensor V3, but I dont have that as an option in my config, only the REV Color/Range Sensor. How do I get the V3 Sensor to appear in my configuration sections … ?

For V1/V2 of the sensor, select: **REV Color/Range Sensor**

For V3 of the sensor, select **Rev Color Sensor v3**

**Comment by Aidan9381** [comment]
> Are you using SDK v5.1 or newer? Also, are you on a Control Hub, or a phone for the RC? Finally, dumb question, but did you try to scroll down on the drop down of I2C devices?

I am using the newest SDK, Im on a phone and yes I did scroll

**Comment by alan412** [comment]
Not to be difficult, but which SDK are you on.   (master is on 5.3 but a
branch with 5.4 is available).   Can you send a picture of the robot
station self inspection?

Also, I have had some weird problems where I had to start over with a new
config.  (ie, I couldn't edit an existing one)

--Alan

**Comment by Aidan9381** [comment]
> Not to be difficult, but which SDK are you on. (master is on 5.3 but a branch with 5.4 is available). Can you send a picture of the robot station self inspection? Also, I have had some weird problems where I had to start over with a new config. (ie, I couldn't edit an existing one)

I am on 5.3 and I can't send an image of self inspection because I just got off of working on it. I will post the screenshot when I am next able to

**Comment by Aidan9381** [comment]
> Not to be difficult, but which SDK are you on. (master is on 5.3 but a branch with 5.4 is available). Can you send a picture of the robot station self inspection? Also, I have had some weird problems where I had to start over with a new config. (ie, I couldn't edit an existing one)

Here are the images of self inspection

**Comment by alan412** [comment]
Hmm.  the images aren't showing up for me.

**Comment by Aidan9381** [comment]
> Hmm. the images aren't showing up for me.

Its probably because my school annoyingly blocks some functions of the website, the images should work this time
![Screenshot_20200130-085858](https://user-images.githubusercontent.com/49820045/73464149-5b964c80-4376-11ea-919b-a69128ca203e.png)
![Screenshot_20200130-085902](https://user-images.githubusercontent.com/49820045/73464150-5c2ee300-4376-11ea-89a5-1f72e8b51cce.png)

**Comment by alan412** [comment]
@Aidan9381 - The problem is that your robot controller needs to be updated.  It is on 5.0, but the v3 of the color sensor only starts in 5.1.   I recommend upgrading the robot controller to either v5.3 or v5.4

**Comment by Aidan9381** [comment]
Thanks for the assistance. That should probably solve the issue, so I will close the issue now as there shouldnt be anything else left to do after that

**Comment by FROGbots-4634** [comment]
Not to mention, if you show up at competition with SDK v5.0, you will fail inspection :)
