### ISSUE TITLE
v5.4 .APK files not on releases page

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/SkyStone#224]
FTA for RI here. At last check v5.4 was released on Google Play but the .APK files are not here on the repo. Looking to get them downloaded for sideloading at championship event this Saturday.

**Comment by ftctechnh** [comment]
HI Tom - The v5.4 changes should be merged now into the master branch of this repo.  You can update your local copy and the APKs should be in the doc/apk subfolder.

Tom

**Comment by cmacfarl** [comment]
The v5.4 Releases entry is available.

https://github.com/FIRST-Tech-Challenge/SkyStone/releases/tag/v5.4
