### ISSUE TITLE
Blocks setDualVelocity is not a function

### ISSUE THREAD

**Issue by slylockfox** [FIRST-Tech-Challenge/SkyStone#248]
in 5.4, using blocks, you can add a dual-motor set block, and change the property from Power to Velocity.  When I ran an opmode like this, the opmode crashed.  The RC log contains this error:

`06-14 20:48:56.099  5054  5432 E RobotCore: BlocksOpMode - "Velocity-Test-2" - main/JavaBridge - caughtException - message is TypeError: motorLAsDcMotor.setDualVelocity is not a function`

The single-motor blocks seem to work correctly.

**Comment by lizlooney** [comment]
Yikes. Looks (from the code) that setDualTargetPositionTolerance might also crash. Thanks for the bug report!

**Comment by lizlooney** [comment]
Actually, I think setDualTargetPositionTolerance is OK. Just setDualVelocity is broke.

**Comment by ftctechnh** [comment]
@slylockfox This will be fixed in a future release of the FTC SDK software.  A change was introduced, tested, and merged into the private repository.  This change will be included with the next release of the software.  Thank you for reporting this issue.
