### ISSUE TITLE
Avoid colliding branch and tag names

### ISSUE THREAD

**Issue by jphigham** [FIRST-Tech-Challenge/SkyStone#25]
At the moment there are both a branch and a tag named `v5.1`. I realize that the `v5.1` branch was merged into `master` and could likely be deleted.

However, I discovered while trying to update forks that Android Studio does not use a `git push` command which can distinguish between the identically-named branch and tag and is rejected by GitHub with a "Updates were rejected because the tag already exists in the remote." error.

The situation can be remedied by a command line push: `git push origin refs/heads/v5.1:refs/heads/v5.1`, but I don't anticipate this would be easy to teach to student team members.

There are conventions that could help. Adhering to the `vN.n` syntax for tag names helps GitHub present the commits as release versions. If you really need to have a branch name that starts with `vN.n`, one option is to add a suffix: `vN.n-branch`.

**Comment by cmacfarl** [comment]
Thanks for the headsup.  The v5.1 branch has been deleted.
