### ISSUE TITLE
Driver for Grove AS5600 magnetic rotary position sensor

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/SkyStone#253]
We wrote a driver for the Grove AS5600 magnetic rotary position sensor. Any chance I can share the code for inclusion into a future release?

**Comment by NoahAndrews** [comment]
I don't speak for FIRST, but we tend to only add drivers for devices that a lot of teams are likely to use.

I'd recommend packaging your driver into a library for teams to easily add to their Android Studio projects.

**Comment by NoahAndrews** [comment]
Turns out that I already made such a repository (I actually started OpenFTC), though it's currently pretty empty. You should make an issue there. https://github.com/OpenFTC/I2C-Drivers

**Comment by cmacfarl** [comment]
It looks like a neat little device at a good price.  I do however agree with @NoahAndrews that it's a great candidate for the OpenFTC library.  OpenFTC has a pretty large following and has been a migration path for other features into the native SDK.    e.g.  Get inclusion into OpenFTC and if a sizeable number of teams ends up using your driver it bubbles to the top of the list of things we want to port into the SDK.
