### ISSUE TITLE
5.5 readme appears to not match code

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/SkyStone#260]
The readme states that there is a new telemetry API method for setting display format.   However, I can't find a new method when I either type in telemetry.  or if I go look at the implementation.

**Comment by FROGbots-4634** [comment]
Hmm, it shows up just fine for me. Did you make sure to resync Gradle?

**Comment by alan412** [comment]
I went and forced a resync and now it has the changes.   I don't know why
it didn't pick up on them changing and resync automatically.    (It still
didn't pull the javadoc though...)
