### ISSUE TITLE
Broken JavaDoc Link in README.md

### ISSUE THREAD

**Issue by lwerner-lshigh** [FIRST-Tech-Challenge/SkyStone#263]
The link in README.md happens to be broken. [https://first-tech-challenge.github.io/SkyStone/doc/javadoc/index.html](https://first-tech-challenge.github.io/SkyStone/doc/javadoc/index.html) Having online documentation would be useful for teams that do not have access to the AndroidStudio version. Should I create a JavaDoc mirror on GitHub?

**Comment by cmacfarl** [comment]
The javadoc has been moved to *-javadoc.jar files hosted alongside the AARs on bintray.  We are working on a better solution for easier navigation independent of AS's builtin javadoc features.  Stay tuned as we continue the migration.

**Comment by lwerner-lshigh** [comment]
I just created a mirror of the JavaDoc [here](https://lasallerobots.github.io/ftc-sdk-docs/index.html) and created a pull request #264

**Comment by cmacfarl** [comment]
Fixed.
