### ISSUE TITLE
VuforiaLocalizer.getCameraCalibration return type changed

### ISSUE THREAD

**Issue by shelbyRobots** [FIRST-Tech-Challenge/SkyStone#269]
We just stepped up to v5.5 from v5.3 and are running into a problem that appears to be due to a change in viuforiaLocalizer.
Previously, getCameraCalibration returned a com.vuforia.CameraCalibration, but now returns a org.firstinspires.ftc.robotcore.internal.camera.calibration.CameraCalibration.
We use the vuforia CameraCalibration that was returned to pass to com.vuforia.Tool.projectPoint to convert points in field/trackable space to pixel coordinates in camera/image space.  We used this to do cropping of the trackable image based on field location info.
This seems to now be broken in v5.5.  Would it be possible to still get the vuforia camera calibration from a vuforiaLocalizer accessor?  Or is possible to somehow convert/construct a vuforia.CameraCalibration from a robotcore cameracalibration
The comments in VuforiaLocalizer still reference a Tool.getProjectionGL(CameraCalibration, float, float) method.

**Comment by FROGbots-4634** [comment]
I believe this should do it for you:

```java
com.vuforia.CameraCalibration camCal = com.vuforia.CameraDevice.getInstance().getCameraCalibration();
```

**Comment by shelbyRobots** [comment]
Excellent - thanks.  That appears to work - or at least build for now.
I will close issue - but technically, V5.5 broke the previous interface by changing the return type of vuforiaLocalizer.getCameraCalibration() to a ftc sdk type with the same name.  Perhaps this should be added to the release notes in the repos readme.
