### ISSUE TITLE
Blocks programmers upgrading last season's op-modes can't tell which blocks are obsolete

### ISSUE THREAD

**Issue by schaferbw** [FIRST-Tech-Challenge/SkyStone#27]
Some Vuforia and TensorFlow blocks need to be reimplemented from season to season.  Specifically, most of the blocks in the the Vuforia and TensorFlow Optimized folders from the Rover Ruckus season have become obsolete because this season's blocks generate different Java calls than last season's.  The Java calls have the season name in the function names but the corresponding blocks do not.  When a team that has developed op-modes for Rover Ruckus attempts to update them to this season they will receive run-time errors but won't know what to do about them. We can tell them to go back to their op modes and look for blocks with the names of blocks mentioned in the run-time error messages but this will be very efficient. A few programmers may notice that the Java code has references to RoverRuckus but Blocks programmers typically are not familiar with Java.  I recommend that the names of the blocks in the Optimized folder include the season name.  It's too late to change the names of the Optimized blocks from last season but if Blocks programmers are told about the issue and they know that all their Optimized blocks need to have Skystone in them they will be able to update their op modes quickly and efficiently.

**Comment by cmacfarl** [comment]
See v5.2
