### ISSUE TITLE
BuildConfig error in internal/FtcRobotControllerActivity.java

### ISSUE THREAD

**Issue by Superman132** [FIRST-Tech-Challenge/SkyStone#270]
After updating his SDK to 5.5, I can't import com.qualcomm.ftcrobotcontroller.BuildConfig, it says that it doesn't exist? Is this just a weird Java error that would work fine on the robot, or did I mess something up while updating my SDK?

**Comment by cmacfarl** [comment]
Are you using AS?  If so, can you please cut and paste the entire build log?  And/or post a screenshot if your AS project?

**Comment by Superman132** [comment]
Figured it out, it was my fault. I forgot to copy the new TeamCode/lib directory to my TeamCode, and once I added it everything worked properly. Thanks for your patience.
