### ISSUE TITLE
Encoder counts appear to be going backward, using RUN_TO_POSITION

### ISSUE THREAD

**Issue by slylockfox** [FIRST-Tech-Challenge/SkyStone#29]
I'm using an Neverest 40 motor, configured correctly, RunMode = RUN_TO_POSITION, motor.TargetPosition = 5000, and telemetry message with motor.CurrentPosition.  I set motor.Power to 1, but the motor goes the same direction with motor.Power set to -1.  I think that's probably correct behavior.  But the value of CurrentPosition starts at zero and goes negative instead of positive.  If I change TargetPosition to -5000, the motor goes the opposite direction, and CurrentPosition goes positive.   Needless to say, the motor never reaches its target position.   This is a blocks opmode from last season, so I'm pretty sure encoder values were positive last season, for a positive TargetPosition.

**Comment by slylockfox** [comment]
I should say, this is with RC app version 5.0 from the play store.

**Comment by rjberry12** [comment]
Have you tried the version of the RC in the sdk? 

Rob Berry

**Comment by FROGbots-4634** [comment]
@slylockfox I've seen encoder wires from AndyMark come with channels A&B reversed before, so you might want to check that.

**Comment by slylockfox** [comment]
Thanks for the advice.  It was the cable, btw this cable from AndyMark, which I see now is known to have wires reversed (grrr): https://www.andymark.com/products/encoder-cable-for-neverest-motor-to-rev-expansion-hub

**Comment by AlecHub** [comment]
As @FROGbots-4634 mentioned, occasionally you'll find that the A&B on NeveRest style encoders are reversed.  It's not the cable's fault.

**Comment by FROGbots-4634** [comment]
@AlecHub Maybe so, but I have personally seen cables from different batches come with the wire colors in different configurations.

**Comment by slylockfox** [comment]
@FROGbots-4634 @AlecHub if you read the reviews on that cable at AndyMark, other buyers stated the wires are reversed on the cable, and they won't work correctly with any Neverest style motor (except maybe one with the switched signal defect).  I have cut and spliced the four I bought, to swap yellow and green, and they work correctly now.

**Comment by AlecHub** [comment]
Thanks @slylockfox & @FROGbots-4634.  Good to be aware of the cabling defects.  I still have the encoders with A&B reversed if AM wants them.
