### ISSUE TITLE
Log Viewer on phone should be improved

### ISSUE THREAD

**Issue by FROGbots-4634** [FIRST-Tech-Challenge/SkyStone#32]
The log viewer on the phone in its current state is arguably of marginal value. However it could be very much improved by performing a few changes:

 - Disabling word wrap
 - Setting font to monospace
 - Set the font color of errors to red

**Comment by FROGbots-4634** [comment]
fixed in v5.5

**Comment by alan412** [comment]
Was 5.5 ever released?

**Comment by FROGbots-4634** [comment]
@alan412  https://github.com/FIRST-Tech-Challenge/SkyStone/tree/20200824-090813-release-candidate#version-55-20200824-090813
