### ISSUE TITLE
Android 3.5 update

### ISSUE THREAD

**Issue by David10238** [FIRST-Tech-Challenge/SkyStone#35]
3.5 released an apply changes replacement to instant run. I wonder if the tech team has put any thought into this and if there is anything in the sdk that this will potentially break.

**Comment by cmacfarl** [comment]
The tech team is aware of the change in AS 3.5.  There's not a lot we can do about it, but monitor the changes.  More information available here: https://android-developers.googleblog.com/2019/08/android-studio-35-project-marble-goes.html

**Comment by darist** [comment]
Perhaps an update to https://github.com/FIRST-Tech-Challenge/SkyStone/wiki/Disabling-Android-Studio-Instant-Run would be helpful since the "Instant Run" option no longer exists.
