### ISSUE TITLE
Driver Station Network doesn't update channel

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/SkyStone#4]
Regardless of which channel, the advanced is used to change it to, it still says "48" on the driver station.

**Comment by rjberry12** [comment]
I am not seeing this, but I am still using the 2 phones. Don’t have the new control hub. 


Rob Berry
Electronimec Systems Corp
We're watching when you can't

**Comment by alan412** [comment]
I am also on two phones.   Both Moto E5 running Android 8.1

**Comment by rjberry12** [comment]
I have 2 E5 plays. Running is 8.0 and am seeing the channel change on the driver station.
Wonder if something broke on 8.1? 
Should I update and see if it breaks?

Rob Berry
Electronimec Systems Corp
We're watching when you can't

**Comment by alan412** [comment]
Figured it out.   A student had set them up to connect to a local WiFi.   Running "Self Inspect" showed the problem.   Making it so they are only on WiFi direct and it works.

**Comment by ftctechnh** [comment]
Hi Alan,

Yes - if it's connected to an infrastructure network (wireless access point) it will default to the channel of that connected network.  

Glad you were able to diagnose the issue. Let us know if you see any other unexpected behavior and thanks for testing this feature out.
