### ISSUE TITLE
Suggestion for adding to README.md

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/SkyStone#43]
Suggest the following to minimize the number of "pull requests" to this repo.

1) Setup your own GitHub repo.
2) clone to your local machine.  (this will make origin your GitHub repo)
3) `git remote add upstream https://github.com/FIRST-Tech-Challenge/SkyStone.git`

Then both to start and whenever a new release comes out:
`git pull upstream master`  (optionally in a branch if your team uses branches)
`git push`  (to update on your GitHub repo)

**Comment by drewwhis** [comment]
You could also add `git remote set-url --push upstream no_push` so that you _can't_ push to upstream.

**Comment by cmacfarl** [comment]
These are great suggestions, but I think that those who may understand what's on offer here are not the target audience.  

Note that over the years, the number of pulls back to FIRST-Tech-Challenge have tapered off.  I don't consider it a huge burden to occasionally walk through and close them.  And it's not overwhelming my inbox (there are other mailers that serve that purpose quite adequately).  And conversely it serves as a learning opportunity for those who open them.
