### ISSUE TITLE
Driver Station won't allow naming of 12345-A-DS

### ISSUE THREAD

**Issue by pmichaud** [FIRST-Tech-Challenge/SkyStone#48]
Phone:  ZTE Speed
Version:  5.2 Driver Station

Attempting to change the Driver Station Name to something like "12345-A-DS" (per RS01) results in a "Controller Name Invalid" error from the app.

I've tried a variety of combinations of team numbers and letters and only the "12345-DS" form seems to work on this device.

Pm

**Comment by cmacfarl** [comment]
This is a holdover from when A was not a legal character per the GDC rules.  12345-DS should work and 12345-B-DS and/or any other character other than A in that space should be fine.

**Comment by CaptainCucurucu** [comment]
I was able to rename with "-A" by first renaming the WiFi Direct network in Android WiFi settings to be consistent with the (e.g. "XXXX-A-RC").

**Comment by ftctechnh** [comment]
If you rename the smartphones as CaptainCucurucu did using the Android WiFi settings you can avoid the character filter:

https://github.com/FIRST-Tech-Challenge/skystone/wiki/Configuring-Your-Android-Devices#renaming-your-smartphones

**Comment by FROGbots-4634** [comment]
@cmacfarl @ftctechnh this can easily be fixed by just changing [`B-Z` to `A-Z` in the regex](https://github.com/OpenFTC/OpenRC-Turbo/blob/8923b3359112163419da653df2d47184ee5398ab/RobotCore/src/main/java/org/firstinspires/ftc/robotcore/internal/network/WifiDirectDeviceNameManager.java#L219).

**Comment by ftctechnh** [comment]
@FROGbots-4634 
We'll put this on the list for release 5.3.  Thanks!

**Comment by cmacfarl** [comment]
Fixed in v5.3
