### ISSUE TITLE
Can't load saved blocks program

### ISSUE THREAD

**Issue by CaptainCucurucu** [FIRST-Tech-Challenge/SkyStone#49]
Running App version 5.2 on Android 7.1.1

After writing a blocks program and saving it, the program is not loaded properly into the blocks editor on subsequent attempts.   Instead, a short default program seems to be shown.  This happens when trying to view/edit the program with a connected laptop, or, when using the "Program and Manage" function within the Robot Controller App.

I have verified that the original program is still in the Robot Controller - it operates per design.   This seems to be a problem loading / viewing it in the block editor.

I have also tried to Download the Op Mode and it appears that the download includes the original logic (based on text editor viewing).

**Comment by ftctechnh** [comment]
@CaptainCucurucu 
Could you make your Blocks op mode that you are having problems with available for us to download to test?  you can make a copy of the op mode and add a ".txt" suffix to the file name and upload it as an attachment to this GitHub issue (click on the "Attach files by dragging & dropping, selecting or pasting them" link below the edit box to Write a new comment).

**Comment by CaptainCucurucu** [comment]
Hello,

I am still having this issue and it seems like it was reported last year without resolution that I can find.   I suspect that it has something to do with the fact that my motor names are different than the sample block code I start from.  But, like the previous report, after reworking the logic to use the correct motor names, saving, exiting, and reloading, I end up with just one or two lines at the start of my block code -- everything else is lost.

Any suggestions?   This is now a total barrier for my team to make progress because we always lose our programs.

**Comment by NoahAndrews** [comment]
Please follow @ftctechnh's instructions to upload the blocks program here.

**Comment by CaptainCucurucu** [comment]
I think I have solved my own problem.

The blocks editor seems to choke when loading a previously saved program that includes an actuator with a space in the name (e.g. “LR Motor”).   On a hunch, I created a new robot config with no spaces in the motor names and now my program seems to load and save reliably.   Maybe this is a previously known issue?

**Comment by NoahAndrews** [comment]
I believe spaces should work. It would help us to figure out the issue for other people if you uploaded the blk file you said you already downloaded.

**Comment by cmacfarl** [comment]
Please reopen and upload your blk file per @ftctechnh's instructions if this is still an issue for you.

**Comment by CaptainCucurucu** [comment]
I think that I figured it out... the issue seems to go away if I remove spaces from the motor names in the robot config (I.e. “LFMotor” instead of “LF Motor”)... guessing may be a known issue already?   I’m not sure why the robot config page lets you pick a name with a space of the whole environment does not support it properly.
