### ISSUE TITLE
Including universal Vuforia key for Java?

### ISSUE THREAD

**Issue by FROGbots-4634** [FIRST-Tech-Challenge/SkyStone#50]
Just curious why Blocks [comes with a universal Vuforia key preloaded](https://github.com/OpenFTC/OpenRC-Turbo/blob/master/Blocks/src/main/assets/CzechWolf) but the Java samples / Vuforia API does not?

**Comment by gearsincorg** [comment]
I believe explicit approval was received from PTC to allow a built-in key for Blocks because it was not openly visible, and available for duplication to other sources.

Note: By publishing it in the OpneFTC source it is possibly violating this agreement, and putting FIRST at risk.

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Yes, Mr. Phil is correct - these are the terms required by PTC.  Please remove references to the key from the open FTC source.  

Also, in my opinion it is not an undue burden to require teams who are using Java to get their own free key.  These are the terms required by PTC and it is important that FIRST comply with these terms.

**Comment by alan412** [comment]
@ftctechnh - To make it easier for teams to comply (and not have keys littered all over GitHub), what about changing the sample code to do: `parameters .vuforiaLicenseKey = hardwareMap.appContext.getString(R.string.vuforiaLicense);`

and then in TeamCode/src/main/res/values/ have a licenses.xml like the one here:
https://github.com/ftc16072/2019preseason/blob/master/TeamCode/src/main/res/values/licenses.template.xml

(That makes it easier for people to do like we have done where we keep the key out of GitHub but doesn't go the full step providing the .gitignore where teams without experience don't understand why it isn't working....)

**Comment by FROGbots-4634** [comment]
@ftctechnh @gearsincorg I'm not entirely sure how to handle this because if I remove it, it will break Blocks. Also I'd like to point out that the key can easily be obtained in the stock SDK by doing:

```java
String universalVuforiaKey = new BufferedReader(new InputStreamReader(AppUtil.getDefContext().getAssets().open("CzechWolf"))).readLine();
```

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Fair enough - but please refrain from directing folks to use the key publicly.

**Comment by FROGbots-4634** [comment]
@ftctechnh @gearsincorg Well, tell you what, I'll delete the contents of the file and direct people to copy their private key into it if they desire to use Blocks.

**Comment by ftctechnh** [comment]
@alan412 
Hi Alan,

I believe that in the case of an Android Studio user, the normal Vuforia SDK terms require that the user have a unique key for the Vuforia Features since they are in effect creating an app using Vuforia's SDK.  I believe this is the legal reasoning that they are using for this requirement.

The OnBot Java is a  bit of a unique case.  Technically the user is not deploying a new APK so it's a little different than the scenario for an Android Studio user.  However, since the On Bot Java template sample op modes are derived/generated by the Android Studio automatically, the sample OnBot Java op modes require that the user provide a key.

**Comment by ftctechnh** [comment]
> @ftctechnh @gearsincorg Well, tell you what, I'll delete the contents of the file and direct people to copy their private key into it if they desire to use Blocks.

@FROGbots-4634 
Thank you FROGbots - you are a _class_ act!

**Comment by FROGbots-4634** [comment]
@ftctechnh I think you misunderstood Alan's comment. He was suggesting a providing a template where users could put their private key that's preconfigured to not be pushed to GitHub so that teams aren't pushing their keys all over the place like they are now.

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Thanks for the clarification.  So the idea is to remove the "INSERT KEY HERE" line and direct the teams to  store it as a resource?  Sounds like a good suggestion.  Let me run this by the developers.

**Comment by FROGbots-4634** [comment]
@ftctechnh yes, but also add a line to the `.gitignore` file to preconfigure the licenses.xml file from being pushed.

**Comment by alan412** [comment]
@ftctechnh @FROGbots-4634 :
Exactly, here is our .gitignore:
https://github.com/ftc16072/2019preseason/blob/master/.gitignore

That way the template file says what to do, and it will fail to compile if a team hasn't done it.

**Comment by ftctechnh** [comment]
@alan412 
Thanks (and I will be sure to read postings more thoroughly in the future!).

**Comment by NoahAndrews** [comment]
Thanks for the clarification. So the idea is to remove the "INSERT KEY HERE" line and direct the teams to store it as a resource? Sounds like a good suggestion. Let me run this by the developers.

@ftctechnh I did some work for the 2017-18 version of OpenRC to make this process easier. Documentation: https://www.openftc.org/openrc/vuforia-key
