### ISSUE TITLE
Download Blocks Programming Tool

### ISSUE THREAD

**Issue by dagilleland** [FIRST-Tech-Challenge/SkyStone#53]
I have searched for the **Blocks Programming Tool** download, but I can't find it anywhere. If *anyone* knows where to download it, please post a direct link to the download here.

**Comment by AlecHub** [comment]
The "FTC Robot Controller" app (from the Play Store) contains Blocks & OnBot Java. The following pages describe how to get started with Blocks:

https://github.com/FIRST-Tech-Challenge/SkyStone/wiki/Configuring-Your-Android-Devices
https://github.com/FIRST-Tech-Challenge/SkyStone/wiki/Writing-an-Op-Mode-with-FTC-Blocks

**Comment by cmacfarl** [comment]
And of course you get the robot controller apk from either the GitHub repo
referenced or the Google Play store.

**Comment by dagilleland** [comment]
I'm not talking about getting the apk that installs on the android phones, I'm talking about the **Blocks *Programming Tool*** that (I presume) I can run on my computer (not my phone). It's the one that looks like this:

![image](https://user-images.githubusercontent.com/2947017/65494385-000cfd00-de72-11e9-9dc2-38cb43b2c44e.png)

**Comment by ftctechnh** [comment]
@dagilleland 
Hi Dan,

The Blocks programming tool is served up by the Robot Controller app.  If you install the Robot Controller app on your Android device, the app will create a Wi-Fi Direct Group (i.e., a wireless network) that you can connect to with your laptop and program using the Blocks or OnBot Java tools.

The Robot Controller acts like an access point and it "serves up" the Blocks application through a web interface hosted on a web server that resides on the Android device.

![image](https://user-images.githubusercontent.com/12596789/65505685-c51dc000-de97-11e9-9575-26a6b64782aa.png)

If you install the Robot Controller app, then you should be good to go.  

I hope this info helps.  Please be sure to checkout the [Blocks Tutorial](https://github.com/FIRST-Tech-Challenge/skystone/wiki/Blocks-Tutorial) and also let us know if you have any additional questions.  [This section](https://github.com/FIRST-Tech-Challenge/skystone/wiki/Connecting-a-Laptop-to-the-Program-&-Manage-Network) of the tutorial shows how to connect a laptop to the Blocks Programming and Manage web page.


Tom

**Comment by NoahAndrews** [comment]
Note that there is an offline version of the Blocks tool which you can download from the Blocks page hosted by the Robot Controller app.

**Comment by lizlooney** [comment]
@dagilleland 
It's important that you configure your robot before using the blocks programming tool. The blocks programming tool will only show blocks for the hardware devices that are in your robot's configuration. For example, if you do not configure your motors, the blocks toolbox will not have any blocks for controlling the motors.
