### ISSUE TITLE
Unable to download Teleop from Android Studio

### ISSUE THREAD

**Issue by SaiVeer04** [FIRST-Tech-Challenge/SkyStone#56]
When I download the code on the phone only the autonomous downloads not the teleop.

Here is the code

`package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotor;

@TeleOp(name = "test",group = "Test")
public class Teleop extends LinearOpMode {

    public DcMotor fr;
    //back right
    public DcMotor br;
    //front left
    public DcMotor fl;
    //back left
    public DcMotor bl;

    //components robot = new components();
    //@Override
    public void runOpMode() throws InterruptedException{

        fr = hardwareMap.dcMotor.get("fr");
        fl = hardwareMap.dcMotor.get("fl");
        br = hardwareMap.dcMotor.get("br");
        bl = hardwareMap.dcMotor.get("bl");

        waitForStart();
        while (opModeIsActive()){

            double r = Math.hypot(gamepad1.left_stick_x, gamepad1.left_stick_y);
            double robotAngle = Math.atan2(-gamepad1.left_stick_y, -gamepad1.left_stick_x) - Math.PI / 4;
            double rightX = (-gamepad1.right_stick_x);
            final double v1 = r * Math.cos(robotAngle) + rightX;
            final double v2 = r * Math.sin(robotAngle) - rightX;
            final double v3 = r * Math.sin(robotAngle) + rightX;
            final double v4 = r * Math.cos(robotAngle) - rightX;

            fl.setPower(v1);
            fr.setPower(v2);
            bl.setPower(v3);
            br.setPower(v4);

            fl.setPower(gamepad1.left_stick_y);

            idle();

        }
    }
}`

**Comment by SaiVeer04** [comment]
Some of it got cut off

**Comment by gearsincorg** [comment]
@TELEOP(name = "test",group = "Test")

Has the wrong capitalization.

TELEOP should be: TeleOp

Since the correct annotation capitalization isn't being used, the code cannot find your teleop opmode.

**Comment by NoahAndrews** [comment]
The capitalization is correct in the original source, that's just GitHub ~~applying weird formatting~~ referencing the user named TELEOP because triple-backticks weren't used correctly.

**Comment by SaiVeer04** [comment]
it was originally TeleOp

**Comment by cmacfarl** [comment]
If this is still a problem for you please reopen and attach logs.  You can obtain logs from the Program and Manage page.

![image](https://user-images.githubusercontent.com/1435639/66959690-c453f600-f01f-11e9-96be-307b7c7e8a60.png)
