### ISSUE TITLE
Unable to synch android studio to the Skystone Master

### ISSUE THREAD

**Issue by Jettt-T** [FIRST-Tech-Challenge/SkyStone#58]

**Comment by cmacfarl** [comment]
I don't understand what this means.  You'll have to be more descriptive for anyone here to effectively help solve your problem.  Error messages, screenshots, logs?

**Comment by m0stlyharmless** [comment]
> 
> 
> I don't understand what this means. You'll have to be more descriptive for anyone here to effectively help solve your problem. Error messages, screenshots, logs?

If I am to venture a guess, what he wants to do is merge the changes from upstream into his downstream repository. 

@Jettt-T, if this is the case, this help article may be helpful:
https://help.github.com/en/articles/syncing-a-fork

**Comment by Jettt-T** [comment]
There is an error that appears right after I have imported this Skystone Master unzipped folder into android studio. The gradle starts to download then all of a sudden (or after about 10-15 seconds I get this
![Screenshot 2019-09-25 at 9 13 29 PM](https://user-images.githubusercontent.com/43526543/65658108-2d28ef00-dfdb-11e9-93d9-4e3a0e9afae3.png)

Android studio will still be functional but .java items will not be recognised. 
![Screenshot 2019-09-25 at 9 28 37 PM](https://user-images.githubusercontent.com/43526543/65658185-77aa6b80-dfdb-11e9-84ac-3421118dafbc.png)

In this picture only the basic java commands will be recognised such as calling variables, but things such as a hardwareMap does not become color coded. And the java files on the left side are orange not blue as they usually are.

**Comment by cmacfarl** [comment]
Still guessing here because I've never seen the problem you are reporting.  

The errors indicate that the gradle sync failed.  Which will result in a project that as you note, will not work properly.  How did you open the project?  I just downloaded the zip file, extracted it, and the from the Android Studio launch dialog selected Import existing project, pointed it at the extracted location and it opened properly.  What might be different about the process you followed?

![image](https://user-images.githubusercontent.com/1435639/65659280-ebe70e00-dfdf-11e9-8acb-1920bd831bf3.png)

**Comment by Jettt-T** [comment]
Nope, that is the exact same process I followed. Yeah, this problem really baffled me to because I normally don't run into this kinda stuff. I imported the SkyStone folder just a few seconds I had unzipped it, and imported it normally.

**Comment by alan412** [comment]
This is the problem you see if you haven't accepted the Android SDK licenses.    Have you accepted them?   (If not, go to Tools...SDK Manager....)

**Comment by cmacfarl** [comment]
> I imported the SkyStone folder just a few seconds I had unzipped it, and imported it normally.

Does this mean the problem has gone away for you?

**Comment by Jettt-T** [comment]
> This is the problem you see if you haven't accepted the Android SDK licenses. Have you accepted them? (If not, go to Tools...SDK Manager....)

Is this really the solution because when I go to tools there is no SDK Manager, I really can't find any of that. I'll try look harder.

**Comment by alan412** [comment]
How old a version of Android Studio do you have?   I suggest downloading
the newest one.....

**Comment by Jettt-T** [comment]
What is the newest version?

**Comment by Jettt-T** [comment]
I think I need to go to file and sync project with all gradle files. I'll try to do both.

**Comment by alan412** [comment]
newest version of Android Studio today is 3.5

**Comment by Jettt-T** [comment]
Thanks so much man.

**Comment by hudsons1033** [comment]
Is Skystone updated for Android Studio 3.5?  I just haven't had a chance yet to try Skystone to know for sure.  There is another thread/issue where they upgraded to AS 3.5 and now things aren't syncing.

**Comment by alan412** [comment]
We are using Android Studio 3.5 and it is working for us.

**Comment by cmacfarl** [comment]
@Jettt-T Is this still an issue for you?  If it is, can you please click on where it says "Show Log in Finder" and then attach the corresponding log file to this issue?

If it is not still an issue, please close.  Thank you.

**Comment by Jettt-T** [comment]
Yes sorry for the late response but I had just downloaded Android Studio 3.5 and it was able to compile, thanks guys!

**Comment by alan412** [comment]
Yay!!!! Have a great season!!!!
