### ISSUE TITLE
Servo.MAX_POSITION is incorrect in OnBot

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/SkyStone#61]
The Servo class constant MAX_POSITION reports a value of zero in OnBot environment. Correctly reports 1 in Android Studio.

Further, on one phone, OnBot, when you type Servo.M brings up MIN_POSITION and MAX_POSITION as autocomplete options. On another phone, Servo.M does not. However both compile and work other than MAX returning zero.

More testing reveals erratic autocomplete behavior. Servo.M brings up the  MIN and MAX as mentioned above. Servo.  may bring up a list of all available items (though when it does, MIN and MAX are not present, even though .M brings them up) and it may not.

**Comment by NoahAndrews** [comment]
This will be fixed in the next release.

**Comment by NoahAndrews** [comment]
Fixed in [version 5.4](https://github.com/FIRST-Tech-Challenge/SkyStone/tree/v5.4)
