### ISSUE TITLE
Unresolved Dependencies

### ISSUE THREAD

**Issue by LovingtonRobotics** [FIRST-Tech-Challenge/SkyStone#63]
We updated to Version 3.5 of Android Studio and now we are getting errors that the files are not syncing with gradle files. It is saying that there are unresolved dependencies. Are we missing any steps?
 
![picture](https://user-images.githubusercontent.com/46681943/65807395-6ed8a780-e14b-11e9-8238-5ca1424288c1.png)

**Comment by IronReignRobotics** [comment]
We ran into this too (android.support), but it was weeks ago so my memory may be fuzzy. We updated AS and were also integrating code from last year. Make sure you've fully updated gradle and the gradle plugin. I think we also had to go through all of our gradle files and check for specific dependency references. I don't think this is a problem if you have a fresh install of the latest AS and just the bare skystone repo and have updated all of your dependency libraries and plugins.

**Comment by LovingtonRobotics** [comment]
We are now trying to run a fresh install of AS and we are trying to open the skystone repository without any added code freshly downloaded. We are getting gradle sync issues saying SSL Peer shut down incorrectly.

**Comment by LovingtonRobotics** [comment]
What gradle plugin version are you using ?

What gradle version?

**Comment by alan412** [comment]
Try a full pull of our code and see if it works for you.  If it does, you
can just delete all of our stuff from the TeamCode folder and move on....

https://github.com/ftc16072/Skystone19-20

--alan

**Comment by LovingtonRobotics** [comment]
We tried it but no luck. Thank you.

**Comment by DanOelke** [comment]
You need to "import" the Skystone project.  Not "Open" it.  (I made that mistake twice - then read the instructions.)  I am pretty sure that was the error message I got at that time.

**Comment by LovingtonRobotics** [comment]
I am pretty sure we are importing it. We hit import project at the very beginning when android studio first opens.

**Comment by LovingtonRobotics** [comment]
I am pretty sure the problem stems from the school filtering system blocking the required plugins that are not installed locally but are retrieved everytime the code runs. It worked on a nonschool internet connection. We have attempted to run offline but the build must be run online the very first time that it is run.
