### ISSUE TITLE
Why I can't run ConceptTensorFlowObjectDetection.java?

### ISSUE THREAD

**Issue by Aaronchen123** [FIRST-Tech-Challenge/SkyStone#83]
"Error: User code threw an uncaught exception: RuntimeException - TFObjectDetector load Model From Asset failed"

How can I solve this problem?

**Comment by FROGbots-4634** [comment]
Are you trying to run a SkyStone sample in <= SDK 5.1?

**Comment by cmacfarl** [comment]
Please reopen with more information on your configuration if this is still a problem for you.
