### ISSUE TITLE
V5.3 not merged

### ISSUE THREAD

**Issue by OviedoRobotics** [FIRST-Tech-Challenge/SkyStone#94]
After 2 weeks why isn’t v5.3 merged into master?  Is it still considered a beta release?

**Comment by cmacfarl** [comment]
The commit date you see is an artifact of how the release is performed.
The v5.3 branch was only pushed to FIRST-Tech-Chalkenge/SkyStone a few days
ago.   The plan was a soft rollout in the branch with a merge next week.
